### ISSUE TITLE
conky clock

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Conky-Collection#12]
![greyconkyclock_by_nixiepro-dbd5spx](https://user-images.githubusercontent.com/10594806/27508746-4139e85a-58ec-11e7-88d0-c9fb9c687004.png)
http://nixiepro.deviantart.com/art/GreyConkyClock-687233445
asked permission to include it

**Comment by Dobbie03** [comment]
I am struggling to get this to work.  Have we included LUA to be built with Conky?

**Comment by erikdubois** [comment]
this should work out of the box
lua is hardware dependent 
let the user choose the aur package they know will work on their system
