### ISSUE TITLE
AL-Left.conkyrc - Updates not displayed

### ISSUE THREAD

**Issue by yodayogi** [ARCHLabs/Archlabs-Conky-Collection#6]
The total number of updates available for the system is not displayed while running the AL-Left conky.

**Comment by yodayogi** [comment]
Update - By expanding the conky width found that when there is 9 updates or less, the value is displayed outside the right border which is why it is not viewed.  If there is more than 9 updates, then the value is displayed with correct alignment.

**Comment by yodayogi** [comment]
Update - Not sure if its a bug or if its the way the command returns the result which is causing the problem.  I have found a workaround to fix the problem and will be updating the conky file after testing it.

**Comment by erikdubois** [comment]
all it need was a space behind 
let us evaluate if that is all it needed...
closing for now
