### ISSUE TITLE
Lua code

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Archlabs-Conky-Collection#9]
Some of the conky's refer to a lua code that is not there.
Keep or delete.
Does anyone have these Lua files?

Will complete the list of conky's later...

**Comment by Dobbie03** [comment]
I think we just delete them.

**Comment by erikdubois** [comment]
there will be more user conky's to add in the future
Op di 13 jun. 2017 om 07:33 schreef Matt <notifications@github.com>

**Comment by erikdubois** [comment]
all fixed in the meantime
